### ISSUE TITLE
How can I join channel with token?🤔

### ISSUE THREAD

**Issue by keisan1231** [AgoraIO/agora-react-native-rtm#10]
login error
`RTMError: 5`

join error
`RTMError: 102`

## my code

```js
async login(uid: string): Promise<any> {
    this.client.createClient(APP_ID);
    return this.client.login({
      token: `${TOKEN}`,
      uid,
    });
  }

  async join(cid: string): Promise<any> {
    return this.client.joinChannel(cid);
  }
```

I enabled App Certificate

**Comment by plutoless** [comment]
you will need a token to login

**Comment by keisan1231** [comment]
@plutoless 

Yes, I genarated token from here🤔

<img width="658" alt="スクリーンショット 2020-06-22 9 04 55" src="https://user-images.githubusercontent.com/46130313/85238210-740f1c80-b467-11ea-9c08-77be6a4bec2d.png">

**Comment by keisan1231** [comment]
Is this token different from that??🤔

**Comment by keisan1231** [comment]
@plutoless 

I see doc.And I tried.
I got this issue😰

https://github.com/AgoraIO/Tools/issues/85#issue-642995707

**Comment by plutoless** [comment]
that temp token is used for RTC only. For RTM currently you will need to generate it yourself.

**Comment by keisan1231** [comment]
Thanks
