### ISSUE TITLE
RTM logout & destroy bricks the app

### ISSUE THREAD

**Issue by arjun9toppiks** [AgoraIO/agora-react-native-rtm#11]
We are currently using the version 1.0.1-alpha.1 published on npmjs.

We are facing a good number of issues with event bindings, logout and destroy methods. We see that the latest code on Github has some fixes for multiple event bindings, but not sure if there are fixes for logout & destroy.

Would like to know if there is any upgrade planned anytime soon? or any beta/alpha versions which we can use?

**Comment by LichKing-2234** [comment]
the plugin will upgrade in Q3-Q4.

**Comment by LichKing-2234** [comment]
fixed
