### ISSUE TITLE
sendRemoteInvitation is not a function

### ISSUE THREAD

**Issue by atlkuk** [AgoraIO/agora-react-native-rtm#15]
![image](https://user-images.githubusercontent.com/7567972/91037087-bb04c400-e608-11ea-848d-f7327a333533.png)

Hi, there is a bug inside RTMEngine.js: inside acceptRemoteNotification there is a function that seems to not exists inside AgoraRTM object

maybe the name of the method could be acceptRemoteNotification?

Thx

**Comment by LichKing-2234** [comment]
fixed in 1.2.2-alpha.2
