### ISSUE TITLE
Gradle version problem

### ISSUE THREAD

**Issue by amod21** [AgoraIO/agora-react-native-rtm#18]
After npm install 

![image](https://user-images.githubusercontent.com/71131732/92922242-1fba7e00-f453-11ea-9a4e-e578e586b5df.png)

**Comment by LichKing-2234** [comment]
I can't see any log about our SDK, seems like your Gradle version not match.

what cmd did you use to run the application? I suggest you use `./gradlew xxx`.

**Comment by amod21** [comment]
Hello Sir ...

I used the following commands ..

Step 1. install node dependencies & link react native modules

Run the below commands in this project folder:

  npm install
  react-native link agora-react-native-rtm
  react-native link react-navigation
  react-native link react-native-gesture-handler
  react-native link react-native-vector-icons


then used

npx react-native run-android

**Comment by LichKing-2234** [comment]
your RN version is `0.59.10`, but your Gradle version > 6.0, it is too new.

**Comment by amod21** [comment]
Hello sir ..

then what should I do?
please help me out ...

**Comment by LichKing-2234** [comment]
you can use the old version of Gradle, such as 4.10.1.

**Comment by amod21** [comment]
Solved
