### ISSUE TITLE
Calling leaveChannel hangs on android and never returns

### ISSUE THREAD

**Issue by aminosman** [AgoraIO/agora-react-native-rtm#21]
```
    @ReactMethod
    public void leaveChannel(String channelId, Promise promise) {
        RtmChannel rtmChannel = channels.get(channelId);
        if (rtmChannel == null) {
            promise.reject("-1", "channel_not_found");
        } else {
            rtmChannel.leave(new ResultCallback<Void>() {
                @Override
                public void onSuccess(Void aVoid) {
                    rtmChannel.release();
                    channels.remove(channelId);
                    promise.resolve(null);
                }

                @Override
                public void onFailure(ErrorInfo errorInfo) {
                    promise.reject(String.valueOf(errorInfo.getErrorCode()), errorInfo.getErrorDescription());
                }
            });
        }
    }
```

I have traced the issue to this method, seems like all is good until we call `rtmChannel.release()` which just hangs. Logcat just prints the error ` E/AGORA_SDK: cannot open log file for writing: agorartm.log, err=30`

**Comment by aminosman** [comment]
Moving `rtmChannel.release();` out of the callback seems to fix the issue. The docs state you should not use release in any callback https://docs.agora.io/en/Real-time-Messaging/API%20Reference/RTM_java/v0.9.1/classio_1_1agora_1_1rtm_1_1_rtm_channel.html#a725d008cb19f44496948ee8f1826deaf

**Comment by LichKing-2234** [comment]
fixed
https://github.com/AgoraIO/agora-react-native-rtm/blob/master/CHANGELOG.md#122-alpha4-2020-12-07
