### ISSUE TITLE
Cannot launch app in IOS 14 cuz signal SIGABRT on RtcEngineManager

### ISSUE THREAD

**Issue by NekoWings** [AgoraIO/agora-react-native-rtm#22]
![image](https://user-images.githubusercontent.com/24478007/95008288-159f3000-064b-11eb-8d2b-fb36fff22dd5.png)
![image](https://user-images.githubusercontent.com/24478007/95008298-2780d300-064b-11eb-9984-c9bc7a24a33a.png)

My runtime version
```package.json
"react-native": "0.63.3",
"react-native-actionsheet": "^2.4.2",
"react-native-agora": "^3.1.2",
```

**Comment by LichKing-2234** [comment]
you can try the `3.1.2-rc.2` version, `3.1.2` will crash when you reload the application on debug mode.

**Comment by NekoWings** [comment]
thanks, I'll try
