### ISSUE TITLE
File and image message support

### ISSUE THREAD

**Issue by jiangwalle** [AgoraIO/agora-react-native-rtm#23]
Hi there,
The native RTM sdk does support sending file and image messages. May I ask if we have a plan to support that feature in RN as well? 

Thanks.

**Comment by LichKing-2234** [comment]
We will support it, but not too soon, because there is no human resource at the moment, and we will be happy if you can contribute code🙂

**Comment by MNoumanImran** [comment]
@LichKing-2234 Thank for your time, we are happy to share and contribute code but we would need your support and time.. our company jamSam is  will to partner.

**Comment by MNoumanImran** [comment]
> We will support it, but not too soon, because there is no human resource at the moment, and we will be happy if you can contribute code🙂

@LichKing-2234 Thank for your time, we are happy to share and contribute code but we would need your support and time.. our company jamSam is will to partner.

**Comment by LichKing-2234** [comment]
thanks

**Comment by plutoless** [comment]
@MNoumanImran maybe you can find contact info in agora website and talk about the cooperation, thanks.

**Comment by peiwenn21** [comment]
current code got support sending file and image messages?? i cant find any function for sending image files

**Comment by MNoumanImran** [comment]
> @MNoumanImran maybe you can find contact info in agora website and talk about the cooperation, thanks.

sure

**Comment by thareekanvar** [comment]
@LichKing-2234 any update about this ?.

**Comment by technostacksnitin** [comment]
Hello @LichKing-2234,

We've integrated Agora RTM SDK in RN. Now, As per need we've to allow user to share PDF / images / Doc etc with end user. But, We're unable to integrate this feature at this moment. Can you please let me know if there is any updates on this issue or any alternatives to share file?

-> Agora RN Library
https://www.npmjs.com/package/agora-react-native-rtm

-> Project React version
"react": "17.0.2"
"react-native": "0.68.2"

Thanks in Advance
Nitinkumar Vaghani

**Comment by LichKing-2234** [comment]
This feature not support at the latest version

**Comment by MNoumanImran** [comment]
Hello AgoraIO/agora-react-native-rtm,
i hope you are doing well.
if you want so we can work together and complete Agora remaining features.
we are good expert in React so Please let me know if that can be possible.

Thanks & Regards
Muhammad Nouman Imran

**Comment by LichKing-2234** [comment]
@MNoumanImran Thanks, but this feature is not support anymore at the 1.5.x version.
