### ISSUE TITLE
Rejoining a channel breaks the app on android

### ISSUE THREAD

**Issue by fluxroom-git** [AgoraIO/agora-react-native-rtm#24]
I leave the channel by client.leaveChannel(), but then when i try to join some other / the same channel with client.joinChannel(), the app crashes on android. iOS works fine though.

also the client.on('error', callback) is **not** fired when the crash occurs.

**Comment by LichKing-2234** [comment]
any crash log?

**Comment by fluxroom-git** [comment]
> any crash log?

unfortunately not, neither did firebase crashlytics catch anything.

**Comment by LichKing-2234** [comment]
you should get the crash log from android logcat

**Comment by fluxroom-git** [comment]
> you should get the crash log from android logcat

yes i have attatched the adb logcat logs

**Comment by Alaaeddine-chakroun** [comment]
Also experiencing the same issue on my end. Android logcat shows the same error message as @fluxroom-git

**Comment by LichKing-2234** [comment]
@fluxroom-git em, but I can't get any useful info.

**Comment by fluxroom-git** [comment]
> @fluxroom-git em, but I can't get any useful info.

you may try reproducing it on your device.

### my react native config
System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-4260U CPU @ 1.40GHz
    Memory: 82.22 MB / 4.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.7.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.1, 30.0.2
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.0/12A7209 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_265 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.3 => 0.63.3
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by LichKing-2234** [comment]
fixed
https://github.com/AgoraIO/agora-react-native-rtm/blob/master/CHANGELOG.md#122-alpha4-2020-12-07
