### ISSUE TITLE
Input enableHistoricalMessaging

### ISSUE THREAD

**Issue by AreKandaru** [AgoraIO/agora-react-native-rtm#25]
Hi!,
**RN RTM SDK** does support for **enable historical messages**?.
In the web version the parameter **enableHistoricalMessaging: true** was sent a channel message.

Thanks.

**Comment by LichKing-2234** [comment]
https://github.com/AgoraIO/agora-react-native-rtm/blob/master/CHANGELOG.md#122-alpha4-2020-12-07
