### ISSUE TITLE
Send message to peer not working anymore

### ISSUE THREAD

**Issue by musmanfaisal** [AgoraIO/agora-react-native-rtm#26]
We have an app with frontend in angular and mobile app in react native. Everthing was working fine about a week ago. Now, the messages are not being sent to the web app from mobile but messages are being received fine from web app to mobile fine.
Anybody else facing this issue?

<img width="995" alt="Screen Shot 2020-11-16 at 7 38 04 PM" src="https://user-images.githubusercontent.com/61688410/99265211-41fdbd00-2843-11eb-8a45-b464f13e0fb0.png">

**Comment by LichKing-2234** [comment]
is this problem still exist?
