### ISSUE TITLE
Sample code is not working and plugin not working with React native

### ISSUE THREAD

**Issue by zainebzaineb** [AgoraIO/agora-react-native-rtm#29]
Hi guys,

I wanna integrate the plugin in my react native project in order to make video&messaging chat, unfortunately i can't even make the sample project work.

Bellow some screenshots of bug i am facing while integrating the plugin in my own demo:

![Bug_code_personal_code](https://user-images.githubusercontent.com/36507391/109315698-1aa78a80-784b-11eb-8c2c-78bc81dddb93.png)
![Bug_Console_personal_project](https://user-images.githubusercontent.com/36507391/109315701-1bd8b780-784b-11eb-8a40-a1ea2c3e684e.png)
![Bug_Simulator_personal_project](https://user-images.githubusercontent.com/36507391/109315703-1c714e00-784b-11eb-85a1-eb2eaf190ce7.png)

And bellow bug while running your example:

![Capture d’écran 2021-02-26 à 15 47 51](https://user-images.githubusercontent.com/36507391/109315808-3b6fe000-784b-11eb-9ea4-0a66cc12a8be.png)
![Capture d’écran 2021-02-26 à 15 48 01](https://user-images.githubusercontent.com/36507391/109315820-3dd23a00-784b-11eb-9545-8265636c29f1.png)

This is my working environment:

![Capture d’écran 2021-02-26 à 15 58 52](https://user-images.githubusercontent.com/36507391/109316130-973a6900-784b-11eb-85d7-1c6e70f9921c.png)

Thank you so much in advance for any kind of help or information

**Comment by LichKing-2234** [comment]
pls show your `git diff`, I need to check the modifying.

**Comment by LichKing-2234** [comment]
I will close this issue, you can reopen it if the issue still exists.
