### ISSUE TITLE
能有个video chat的demo吗，谢谢

### ISSUE THREAD

**Issue by lostomato** [AgoraIO/agora-react-native-rtm#3]
发起视频邀请是怎么实现的

**Comment by Matrixbirds** [comment]
可以的 我们会出一个初版demo 

视频邀请主要是由发起邀请和同意邀请两个阶段组成 你可以在[文档](https://agoraio.github.io/agora-react-native-rtm/latest/)里找到相关的事件名

**Comment by LichKing-2234** [comment]
you can reopen this issue if the problem still exists.
