### ISSUE TITLE
Type definition for RTMEventCallback is incorrect

### ISSUE THREAD

**Issue by EkaanshArora** [AgoraIO/agora-react-native-rtm#30]
The type for RTMEventCallback is defined as `export declare type RTMEventCallback = () => {};` which seems incorrect as it gives a lint error on usage of the callback.
For example:
```
this._rtmEngine.on('error', (evt) => {
  console.log(evt);
});
```
Gives an error - `Argument of type '(evt: any) => void' is not assignable to parameter of type 'RTMEventCallback'.`

Edit: I see the code for the correct types on this repo but it's not available in the latest stable version released to [NPM](https://www.npmjs.com/package/agora-react-native-rtm). Is there a possibility to push a fix for the stable release, so that the users aren't thrown off by linter errors till the alpha version is released?

**Comment by LichKing-2234** [comment]
Sorry, I cant find `RTMEventCallback`, where is it?

**Comment by EkaanshArora** [comment]
The problem is on `v1.2.2-alpha.3`, the stable release on NPM.
You can find the definition here on line 14 - https://github.com/AgoraIO/agora-react-native-rtm/blob/5b5ec4cd6f559465c516d7b90c8b432a42413b39/src/types.ts

**Comment by LichKing-2234** [comment]
pls use the `v1.2.2-alpha.6`

**Comment by LichKing-2234** [comment]
I will close this issue, you can reopen it if it still exists.
