### ISSUE TITLE
No channel attribute operations

### ISSUE THREAD

**Issue by sheyDev** [AgoraIO/agora-react-native-rtm#32]
Does this sdk not have the channel attribute operations like get and set channel attributes?

**Comment by LichKing-2234** [comment]
Sure. you can find it here.

https://github.com/AgoraIO/agora-react-native-rtm/blob/master/src/RtmEngine.ts#L601

**Comment by sheyDev** [comment]
I was using v1.2.2 alpha.3
Thanks @LichKing-2234
