### ISSUE TITLE
Thread 2 EXC_BAD_ACCESS code 1 address = 0x0

### ISSUE THREAD

**Issue by sheyDev** [AgoraIO/agora-react-native-rtm#34]
Im getting a error in xcode when getUserAttributes is called after a new user joins the channel.
Error occurs at AgoraRTM.m line 286 [self.rtmKit getUserAllAttributes

How can I resolve this. Happens 100% of times

**Comment by sheyDev** [comment]
If the external user is already in the channel when the iOS app user joins, this error doesnt occur

**Comment by RoJoHub** [comment]
Sorry to reply you so late 
@sheyDev
-------
Currently our error object cannot be printed directly.

In the next release, we will improve the error code prompt information of our SDK.

Now. please use
```
catch((e)=>{
    console.log(‘code:',e.code);
})
```

-------
Error code For AgoraRtmProcessAttributeErrorCode : [AgoraRtmProcessAttributeErrorCode](https://docs.agora.io/en/Real-time-Messaging/API%20Reference/RTM_oc/Constants/AgoraRtmProcessAttributeErrorCode.html)

------


Please adjust the response code according to the error message

Hope this helps you

**Comment by sheyDev** [comment]
Hi @RoJoHub how do i get that?

**Comment by sheyDev** [comment]
<img width="1396" alt="Screen Shot 2021-03-23 at 3 22 14 pm" src="https://user-images.githubusercontent.com/52515689/112092450-a06cea80-8beb-11eb-8f05-d10656b11977.png">

**Comment by RoJoHub** [comment]
<img width="1441" alt="WX20210323-144233@2x" src="https://user-images.githubusercontent.com/15648309/112104461-30a83100-8be6-11eb-88ec-ffddc0ba2ab4.png">

Thank you !
Please add breakpoints, xcode can show more.

**Comment by LichKing-2234** [comment]
Seem like you not call the `createInstance` method, or it has been released.

**Comment by RoJoHub** [comment]
But sending a message to nil will not cause a crash.
