### ISSUE TITLE
i think that's  RtmEngine  init problem, can i get some help?

### ISSUE THREAD

**Issue by ytt123** [AgoraIO/agora-react-native-rtm#36]
![image](https://user-images.githubusercontent.com/13364695/114001299-61e35b00-988e-11eb-998b-e47321450ac3.png)
![image](https://user-images.githubusercontent.com/13364695/114001322-690a6900-988e-11eb-85d7-cd191edee674.png)

**Comment by LichKing-2234** [comment]
you should use it like this.
```
engine.current = new RtmEngine()
await engine.current.createClient(appId)
```

**Comment by ytt123** [comment]
another  problem : 
I receive some warning  ， such as Sending `ag_rtm_connectionStateChanged` with no listeners registered.
besides
![image](https://user-images.githubusercontent.com/13364695/114007728-277cbc80-9894-11eb-8021-46550bf11479.png)
I can not step into  this function.

**Comment by LichKing-2234** [comment]
pls refer to our example

**Comment by ytt123** [comment]
I want to get  more info about getUserAttributesByUid usege
such as  get the  usename ,your example seem to have no refer

**Comment by RoJoHub** [comment]
Hi. friend. Please refer to this.The relevant discussion will be there
https://github.com/AgoraIO/agora-react-native-rtm/issues/33#issuecomment-810792322

**Comment by bhaktitud** [comment]
> pls refer to our example

I did, but after upgrading to the latest version v1.4.8 i cannot event send a channelMessage, can you update the example please?

**Comment by thuantvDr4** [comment]
> #33 (comment)

@ytt123 , function login() take in param is object = { uid: '',  token: ''} ;
this is, my function and it working
![image](https://user-images.githubusercontent.com/24288310/163538177-ccf4eab2-ebc6-422a-a810-cc62f26a5ccc.png)
 i hope helpul fo you
