### ISSUE TITLE
Issue with RTM events trigger

### ISSUE THREAD

**Issue by IrimieAndreiREEA** [AgoraIO/agora-react-native-rtm#37]
Hello. I am not sure if this is a known issue or I am doing something wrong but I am struggling with the events for messages: **channelMessageReceived** and **messageReceived** which as far as I see they are not called. They are attached in a function (initRTM) that is called in componentDidMount() of the component. Here is the complete code: https://pastebin.com/XL3XUDYM Do you have any idea about what the possible issue might be?

Also I can confirm that the messages are sent using .sendMessageByChannelId() since the .done() method is called on it. The only issue that remains is that once I send a message using sendMessageByChannelId, I expect an event to be called (no event is triggered).  Neither  messageReceived  or channelMessageReceived are called. They appear to not respond to anything and I am not able to find out why… 

I'm using Agora 3.2.2 and Agora RTM 1.2.2-alpha.6
Any idea why this happens?

**Comment by RoJoHub** [comment]
Hi. friend. Please refer to this.
https://github.com/AgoraIO/agora-react-native-rtm/issues/33#issuecomment-810792322
