### ISSUE TITLE
Not getting any response from messageReceived/channelMessageReceived

### ISSUE THREAD

**Issue by peiwenn21** [AgoraIO/agora-react-native-rtm#39]
this._rtmEngine.on('messageReceived', (evt) => {
            let { uid, channelId, text } = evt;
            let data = text.split(':');
            this.setState({rooms: {...this.state.rooms, [data[0]]: data[1]}});
});

i cant get any data return from this function, and i can sure i have success send out my message. Any idea how to solve it?

**Comment by LichKing-2234** [comment]
print the value of `evt`?
