### ISSUE TITLE
ios 端无法接收到web端joinChannel的事件

### ISSUE THREAD

**Issue by sihuayin** [AgoraIO/agora-react-native-rtm#4]
1. web端登录并且加入频道成功，处于等待状态。
2. ios端 登录并加入频道成功
3. web端收到 有用户加入， 即 memberJoind事件触发。

而
1. ios端 登录并加入频道成功，处于等待状态。
2. web端登录并且加入频道成功
3. ios 端没有触发memberJoined 的代理函数。

这个问题有遇到过吗？

**Comment by Matrixbirds** [comment]
[rtm tutorials](https://webdemo.agora.io/agora-web-showcase/examples/Agora-RTM-Tutorial-Web/) 你可以尝试通过这里的web端demo和iOS的[chatsapp](https://github.com/AgoraIO/agora-react-native-rtm/tree/master/examples/chatsapp)复现吗？

**Comment by LichKing-2234** [comment]
you can reopen this issue if the problem still exists.
