### ISSUE TITLE
[Android] Cannot build in gradle 4.0 and above gradle verseion.

### ISSUE THREAD

**Issue by Saehanseul** [AgoraIO/agora-react-native-rtm#48]
Hello.
This module is build well in gradle 3.x.x. 
But can not build in gradle 4.x.x.

[error]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':agora-react-native-rtm:compileDebugKotlin'.
> Could not resolve all artifacts for configuration ':agora-react-native-rtm:debugCompileClasspath'.
   > Could not find rtm-sdk-1.4.7.jar (com.github.agorabuilder:rtm-sdk:1.4.7).
     Searched in the following locations:
         https://www.jitpack.io/com/github/agorabuilder/rtm-sdk/1.4.7/rtm-sdk-1.4.7.jar

[version]
"agora-react-native-rtm": "^1.4.8",
"react": "16.13.1",
"react-native": "0.63.3",

**Comment by LichKing-2234** [comment]
@medlJeremy The latest version has fixed this issue.

**Comment by bledi-piperku** [comment]
@LichKing-2234 Im facing the same issue. React Native CLI

**Comment by abraaoduarte** [comment]
I'm still having this problem with the version `1.4.8`, is there a solution?

**Comment by bledipiperku** [comment]
> I'm still having this problem with the version `1.4.8`, is there a solution?

Upgrade to version 1.5.0
