### ISSUE TITLE
examples/chatsapp 无法运行

### ISSUE THREAD

**Issue by hiscc** [AgoraIO/agora-react-native-rtm#5]
1. 按照流程进行到 pod install 时提示 
``[!] CocoaPods could not find compatible versions for pod "AgoraRtm_iOS":
  In Podfile:
    agora-react-native-rtm (from `../node_modules/agora-react-native-rtm`) was resolved to 1.0.1-alpha.1, which depends on
      AgoraRtm_iOS (= 1.0.1)``

2. 然后修改 package.json 中的 agora-react-native-rtm 版本降级到 1.0.0-alpha.1  再次 pod install 后成功
3. 用 Xcode 打开项目出现各种神奇的错误。。。。 

所以我该如何解决问题？是因为 agora-react-native-rtm  版本问题还是项目相关库的构建问题？

**Comment by Matrixbirds** [comment]
麻烦提供一下比较全的报错信息
