### ISSUE TITLE
Accept invitation not working in iOS

### ISSUE THREAD

**Issue by Yasvita** [AgoraIO/agora-react-native-rtm#52]
Hello, I'm using agora-react-native-rtm to handle call invitation. It works fine on Android, However, on iOS the acceptRemoteInvitationV2 method fails with error code 1. 

I'm using 
react-native: 0.66.4
xcode: 12.5.1
agora-react-native-rtm: 1.4.8

can anyone please suggest me any solution for this @plutoless @LichKing-2234  @Matrixbirds  @vitoresende ?

**Comment by Yasvita** [comment]
Somehow in iOS in invitation hash value needs to be 0, so we need to change hash value of invitation  before accept/refuse then only it will work in iOS while in android no this kind of change is required, Anyways thanks!

**Comment by kbwo** [comment]
> Somehow in iOS in invitation hash value needs to be 0
I was having same problem. Now it works according to your solution. Thanks!

**Comment by jorgerojas26** [comment]
Indeed, @Yasvita solution is working.
