### ISSUE TITLE
Build fails on M1 machine

### ISSUE THREAD

**Issue by gus-delpino** [AgoraIO/agora-react-native-rtm#53]
Hello,
I am running into issues running my app after install this dependency on an M1 machine. I am running
React Native: 66.3
agora-react-native-rtm: 1.4.8
xcode: 13.1
Machine: Apple M1

When running the app, I get: 
ld: building for iOS Simulator, but linking in dylib built for iOS, file '/Users/gustavodelpino/dev/blink/BlinkMobile/ios/Pods/AgoraRtm_iOS/AgoraRtmKit.framework/AgoraRtmKit' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I appreciate any help you can provide!

**Comment by LichKing-2234** [comment]
https://stackoverflow.com/questions/63607158/xcode-12-building-for-ios-simulator-but-linking-in-an-object-file-built-for-io

**Comment by maxxfrazer** [comment]
@LichKing-2234 the next RTM release will fix this issue without any need for manual changes like this.
how soon after release can this repo be updated?

**Comment by dgillier** [comment]
@maxxfrazer When could we expect a fix on this ?
Thanks !

**Comment by daiki1003** [comment]
@maxxfrazer 
Though I am using Flutter package for agora, I'm attacking the same issue too.
Is this already fixed or only physical devices?

**Comment by LichKing-2234** [comment]
> https://stackoverflow.com/questions/63607158/xcode-12-building-for-ios-simulator-but-linking-in-an-object-file-built-for-io

Pls refer to this.
