### ISSUE TITLE
The library is marked as deprecated

### ISSUE THREAD

**Issue by JesusDiedSoYouCanHaveEternalLife** [AgoraIO/agora-react-native-rtm#57]
Why are all the functions deprecated?
createClient(), login() etc

**Comment by LichKing-2234** [comment]
@deprecated {@link createInstance}

**Comment by LichKing-2234** [comment]
pls refer to the comments to use the new function

**Comment by JesusDiedSoYouCanHaveEternalLife** [comment]
Ok thank you very much. I appreciate the work you guys are doing God bless.
