### ISSUE TITLE
 RN 0.60 support ?

### ISSUE THREAD

**Issue by cristianmgb** [AgoraIO/agora-react-native-rtm#6]
Hello, does this library have support for RN 0.60? I am using RN 0.60.5 and I need to integrate the chat option, I am already using Agora RN VideoCall.

Thanks.

**Comment by Matrixbirds** [comment]
Yes, It support since 0.55, you can use it in any future react native version.

**Comment by ytt123** [comment]
> Hello, does this library have support for RN 0.60? I am using RN 0.60.5 and I need to integrate the chat option, I am already using Agora RN VideoCall.
> 
> Thanks.

can you support an   Richer  demo used Agora RN videoCall for me reference
