### ISSUE TITLE
Issue with minSdkVersion

### ISSUE THREAD

**Issue by NitayRabi** [AgoraIO/agora-react-native-rtm#66]
Issues when using React 0.68.0 and minSdkVersion: 21
See: https://lifesaver.codes/answer/android-build-fails-for-libs-with-minsdkversion-17-with-react-native-0-64-2712 
&
See: https://github.com/AgoraIO/agora-react-native-rtm/pull/65

**Comment by LichKing-2234** [comment]
communicate on #65
