### ISSUE TITLE
你敢用，它就赶坑，绝无夸张

### ISSUE THREAD

**Issue by Evan-Future** [AgoraIO/agora-react-native-rtm#7]
很负责的说，包括RTC的库，我们使用了，有好几处bug 以及引起的各种恶心的闪退/卡死问题(Android)，我们长时间寻找问题根源，一处问题是官方文档写了不能使用的方式(很不起眼的角落注明的)这个库也用了，导致APP卡死。闪退问题更是恶心，这个库闪退是100%存在。不用怀疑，特别是初次使用就会出现。不要说是我们代码功底，逻辑思维什么之类的问题。于是我们在不得已尝试多个方法后在崩溃边缘猜测的最后一个可能，终于解决了。但是我不会分享这些问题的根本原因及解决方法，因为官方的支持也是很恶心的各种抬杠。

对于这种官方出的库，不用说测试不全面了，很多基本测试都没有。所以谁用谁认灾吧。祝你们好运！！！呵呵

**Comment by plutoless** [comment]
很抱歉给你带来不愉快的使用体验，今后如果有需要还是可以把社区SDK相关的问题同步在对应的仓库issue里，我们这边会同步尽可能帮你解决问题并改善体验的

**Comment by Evan-Future** [comment]
> 很抱歉给你带来不愉快的使用体验，今后如果有需要还是可以把社区SDK相关的问题同步在对应的仓库issue里，我们这边会同步尽可能帮你解决问题并改善体验的

一个产品是不断完善的，但是你们的支持(电话售前拉的所谓技术支持)我想说就是抬杠的，而且态度并不是帮使用的客户解决问题的心态，而是觉得自己一定要“赢”了这个口舌仗。
因为使用你们这个RTM组件造成的闪退问题导致频繁闪退，产品稳定性太差，客户已经基本宣告项目失败。

**Comment by Matrixbirds** [comment]
这块可以提供一下组件造成闪退问题的现象和RTM组件相关的日志么？

**Comment by plutoless** [comment]
> > 很抱歉给你带来不愉快的使用体验，今后如果有需要还是可以把社区SDK相关的问题同步在对应的仓库issue里，我们这边会同步尽可能帮你解决问题并改善体验的
> 
> 一个产品是不断完善的，但是你们的支持(电话售前拉的所谓技术支持)我想说就是抬杠的，而且态度并不是帮使用的客户解决问题的心态，而是觉得自己一定要“赢”了这个口舌仗。
> 因为使用你们这个RTM组件造成的闪退问题导致频繁闪退，产品稳定性太差，客户已经基本宣告项目失败。

理解，我找技术支持沟通一下看下可能是什么问题

**Comment by Evan-Future** [comment]
> 这块可以提供一下组件造成闪退问题的现象和RTM组件相关的日志么？

[agora-rtm.log](https://github.com/AgoraIO/agora-react-native-rtm/files/4082720/agora-rtm.log)

**Comment by hiscc** [comment]
> 很负责的说，包括RTC的库，我们使用了，有好几处bug 以及引起的各种恶心的闪退/卡死问题(Android)，我们长时间寻找问题根源，一处问题是官方文档写了不能使用的方式(很不起眼的角落注明的)这个库也用了，导致APP卡死。闪退问题更是恶心，这个库闪退是100%存在。不用怀疑，特别是初次使用就会出现。不要说是我们代码功底，逻辑思维什么之类的问题。于是我们在不得已尝试多个方法后在崩溃边缘猜测的最后一个可能，终于解决了。但是我不会分享这些问题的根本原因及解决方法，因为官方的支持也是很恶心的各种抬杠。
> 
> 对于这种官方出的库，不用说测试不全面了，很多基本测试都没有。所以谁用谁认灾吧。祝你们好运！！！呵呵

官方的回答是：RTC、RTM 是社区维护的推荐我们用原生库😂😂😂，那样稳
