### ISSUE TITLE
setChannelAttributes accept array in mobile sdk and object in web sdk

### ISSUE THREAD

**Issue by yasvitajoshi309** [AgoraIO/agora-react-native-rtm#73]
Hello all, we are using "agora-react-native-rtm": "^1.5.0", in react native and in "agora-web-sdk": 1.5.0 in web so it creates issue like invalid parameter to communicate between cross platform can you suggest how to fix this or can you suggest any other alternative to communicate if any ! Any help would be highly appreciated

**Comment by plutoless** [comment]
@yasvitajoshi309 you can provide different params depending on platform.

**Comment by yasvitajoshi309** [comment]
@plutoless thanks it's working for different types also in both platforms as you said!

Now we are facing issue in acceptRemoteInvitationV2 on iOS 

For, agora-react-native-rtm version 1.4.8 it was working if we change remote invitation hash value to 0 and then call accept/refuse invitation but after upgrading agora-react-native-rtm version 1.5.0 it stop working that workaround also can you please help?

**Comment by yasvitajoshi309** [comment]
Sorry for the inconvenience, it was my mistake working fine after changing hash value to 0 of remote invitation in this(agora-react-native-rtm: 1.5.0) version also, Thanks!
