### ISSUE TITLE
acceptRemoteInvitationV2 fails on iOS

### ISSUE THREAD

**Issue by HalilFocic** [AgoraIO/agora-react-native-rtm#74]
Hi. I am using agora-react-native-rtm and I am having trouble with accept remote invitation on iOS devices. Basically if i have 2 phones and I use iOS to call and android to answer, everything works fine. But if i call from android to iOS when I press accept i get unhandled promise and SDK doesn't even send event 'RemoteInvitationAccepted'  on iOS or 'LocalInvitationAccept' on Android.

Anyone know what could I have done wrong?

**Comment by yasvitajoshi309** [comment]
Same issue here we are using ios and web sdk, for agora-react-native-rtm version 1.4.8 it was working if we change remote invitation hash value to 0 and then call accept/refuse invitation but after upgrading agora-react-native-rtm version 1.5.0 can someone please help!

**Comment by yasvitajoshi309** [comment]
Sorry for the inconvenience, it was my mistake working fine after changing hash value to 0 of remote invitation in this(agora-react-native-rtm: 1.5.0) version also, Thanks!

**Comment by ShelbyIB** [comment]
@yasvitajoshi309 @HalilFocic I wonder how to change hash value to 0  since hash is a read only property for LocalInvitation and RemoteInvitation?

```
export interface LocalInvitation
{
readonly calleeId: string;
content?: string;
channelId?: string;
readonly response?: string;
readonly state?: LocalInvitationState;
readonly hash: number;
}
```
```
export interface RemoteInvitation {
  readonly callerId: string;
  readonly content?: string;
  readonly channelId?: string;
  response?: string;
  readonly state?: RemoteInvitationState;
  readonly hash: number;
}
```
