### ISSUE TITLE
打包上传到Google商店提示“有缺陷的版本：  OpenSSL 1.1.1h in lib/x86/libagora-rtm-sdk-jni.so”

### ISSUE THREAD

**Issue by showtan001** [AgoraIO/agora-react-native-rtm#83]
我看官网sdk 1.5.3版本OpenSSL已经升级到1.1.1q了，但是我这边提示还是OpenSSL 1.1.1h
![image](https://user-images.githubusercontent.com/32892347/217463406-156e05ac-e0fa-4bcb-9275-436d50dff151.png)
![image](https://user-images.githubusercontent.com/32892347/217463580-03b8c1f2-0520-46d0-8404-eb393062eac2.png)

**Comment by LichKing-2234** [comment]
react-native的库需要使用1.5.1版本
https://github.com/AgoraIO/agora-react-native-rtm/blob/v1.5.1/android/build.gradle#L130

**Comment by showtan001** [comment]
> react-native的库需要使用1.5.1版本 https://github.com/AgoraIO/agora-react-native-rtm/blob/v1.5.1/android/build.gradle#L130

SDK如果升级到1.5.3消息发送功能就没有了，这个该如何解决？
![11411677046814_ pic](https://user-images.githubusercontent.com/32892347/220541781-f47b5a50-3419-432d-8874-615b8c20e4a1.jpg)
