### ISSUE TITLE
你好，rn中，我离开界面的时候调的离开视频直播通道，离开实时聊天通道的时候报错了。他们都是异步的

### ISSUE THREAD

**Issue by jiyunkeji** [AgoraIO/agora-react-native-rtm#9]
![Uploading 9469A14F8CDB7AEC776B940810E382B2.jpg…]()
![B2B6FAB37AFD75D3AC9195FD66992B34](https://user-images.githubusercontent.com/50569560/82403092-9b518300-9a90-11ea-8ba0-bb79f328bb3d.jpg)
![49B0CECE4770F9A623BDF0C582385F6D](https://user-images.githubusercontent.com/50569560/82403095-9c82b000-9a90-11ea-8b80-1b89d79feac0.jpg)
<img width="375" alt="image" src="https://user-images.githubusercontent.com/50569560/82403164-c4721380-9a90-11ea-992a-46dd60a01a6e.png">

**Comment by plutoless** [comment]
你在离开后有去更新UI状态吗？感觉是因为component已经销毁了但你还是尝试去更新UI状态导致的

**Comment by jiyunkeji** [comment]
> 你在离开后有去更新UI状态吗？感觉是因为component已经销毁了但你还是尝试去更新UI状态导致的

<img width="395" alt="image" src="https://user-images.githubusercontent.com/50569560/82632395-ab9d6580-9c2a-11ea-8307-d5ed6ee31155.png">
rtc有个显示隐藏AgoraView，不设置false，会退出去了还在。
上面这个图是我把设置state注释了，还是报错

**Comment by jiyunkeji** [comment]
> > 你在离开后有去更新UI状态吗？感觉是因为component已经销毁了但你还是尝试去更新UI状态导致的
> 
> <img alt="image" width="395" src="https://user-images.githubusercontent.com/50569560/82632395-ab9d6580-9c2a-11ea-8307-d5ed6ee31155.png">
> 
> rtc有个显示隐藏AgoraView，不设置false，会退出去了还在。 上面这个图是我把设置state注释了，还是报错

这个在ios才会报错，真奇怪

**Comment by plutoless** [comment]
看起来是同一个回调触发了好几次，你能用我们的官方demo复现这个问题吗
