### ISSUE TITLE
Asset validation failed Invalid Executable. The executable 'my_app_name.app/Frameworks/AgoraRtmKit.framework/AgoraRtmKit' contains bitcode

### ISSUE THREAD

**Issue by Parathantl** [AgoraIO/agora-react-native-rtm#94]
When testing or locally checking the application, there are no issues at all.

However, it provides the above-mentioned issue after building and archiving the app through Xcode.

Does anyone have the same issue? All the Xcode version and React Native versions are latest

**Comment by guoxianzhe** [comment]
@Parathantl check this https://github.com/AgoraIO-Extensions/react-native-agora/issues/826#issuecomment-2375777280

**Comment by Parathantl** [comment]
@guoxianzhe The StackOverflow answer solved this. Should we always have this shell script to remove bit code whenever we archive the app? 

Any permanent solution?

**Comment by showtan001** [comment]
> @guoxianzhe The StackOverflow answer solved this. Should we always have this shell script to remove bit code whenever we archive the app?
> 
> Any permanent solution?

How was it resolved?

**Comment by guoxianzhe** [comment]
@Parathantl 

you can try this package:  https://github.com/AgoraIO-Extensions/agora-react-native-rtm/issues/20#issuecomment-2398543360

We are planing to release a new rtm sdk for react-native in the future. Currently is alpha version.

**Comment by Parathantl** [comment]
Okay great. I will check out & thanks for your reply on this issue.

**Comment by HardikTechno** [comment]
Hello
I have resolved this issue after add below code in post_install in Pod file and then pod install

Xcode Version : 16.2
"agora-rn-uikit": "^5.0.2",
"react-native-agora": "^4.4.0",
"agora-react-native-rtm": "^1.5.1",
"react-native": "0.75.4"

post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    
    **bitcode_strip_path = `xcrun --find bitcode_strip`.chop!
       def strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
         framework_path = File.join(Dir.pwd, framework_relative_path)
         command = "#{bitcode_strip_path} #{framework_path} -r -o #{framework_path}"
         puts "Stripping bitcode: #{command}"
         system(command)
       end

       framework_paths = [
         "Pods/AgoraRtm_iOS/AgoraRtmKit.xcframework/ios-arm64_armv7/AgoraRtmKit.framework/AgoraRtmKit",
         "Pods/AgoraRtm_iOS/AgoraRtmKit.xcframework/ios-arm64_i386_x86_64-simulator/AgoraRtmKit.framework/AgoraRtmKit"
       ]

       framework_paths.each do |framework_relative_path|
         strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)**
       end
  end

**Comment by TheScalion** [comment]
> Hello I have resolved this issue after add below code in post_install in Pod file and then pod install
> 
> Xcode Version : 16.2 "agora-rn-uikit": "^5.0.2", "react-native-agora": "^4.4.0", "agora-react-native-rtm": "^1.5.1", "react-native": "0.75.4"
> 
> post_install do |installer| # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202 react_native_post_install( installer, config[:reactNativePath], :mac_catalyst_enabled => false, # :ccache_enabled => true )
> 
> ```
> **bitcode_strip_path = `xcrun --find bitcode_strip`.chop!
>    def strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
>      framework_path = File.join(Dir.pwd, framework_relative_path)
>      command = "#{bitcode_strip_path} #{framework_path} -r -o #{framework_path}"
>      puts "Stripping bitcode: #{command}"
>      system(command)
>    end
> 
>    framework_paths = [
>      "Pods/AgoraRtm_iOS/AgoraRtmKit.xcframework/ios-arm64_armv7/AgoraRtmKit.framework/AgoraRtmKit",
>      "Pods/AgoraRtm_iOS/AgoraRtmKit.xcframework/ios-arm64_i386_x86_64-simulator/AgoraRtmKit.framework/AgoraRtmKit"
>    ]
> 
>    framework_paths.each do |framework_relative_path|
>      strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)**
>    end
> ```
> 
> end

Thanks this work for me i have spend lot's of times on this. Thank you Again
